title: DevSet
description: Development Standards and Tooling
url: https://toxicoder.github.io
baseurl: /devset
remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
- jekyll-optional-front-matter
- jekyll-seo-tag
- jekyll-feed
permalink: pretty
defaults:
- scope:
    path: ''
  values:
    layout: doc
    sidebar:
      nav: "docs"
