site_name: DevSet
site_url: https://toxicoder.github.io/devset/
repo_url: https://github.com/toxicoder/devset
repo_name: toxicoder/devset

theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

nav:
  - Home: index.md
  - Job Role Organization:
      - Overview: job_roles/job_role_organization.md
      - 3.0 Executive Leadership:
          - CEO: job_roles/executive_leadership/ceo.md
          - CFO: job_roles/executive_leadership/cfo.md
          - CLO: job_roles/executive_leadership/clo.md
          - CPO: job_roles/executive_leadership/cpo.md
          - CRO: job_roles/executive_leadership/cro.md
          - CTO: job_roles/executive_leadership/cto.md
      - 3.1 Engineering & Technology:
          - VP of Engineering: job_roles/engineering__technology/vp_of_engineering.md
          - Director of App Dev: job_roles/engineering__technology/director_of_app_dev.md
          - Director of Infrastructure: job_roles/engineering__technology/director_of_infrastructure.md
          - Backend Engineer: job_roles/engineering__technology/backend_engineer.md
          - Data Engineer: job_roles/engineering__technology/data_engineer.md
          - Frontend Engineer: job_roles/engineering__technology/frontend_engineer.md
          - Mobile Engineer: job_roles/engineering__technology/mobile_engineer.md
          - QA Engineer: job_roles/engineering__technology/qa_engineer.md
          - Security Engineer: job_roles/engineering__technology/security_engineer.md
          - Site Reliability Eng: job_roles/engineering__technology/site_reliability_eng.md
          - Software Engineer: job_roles/engineering__technology/software_engineer.md
      - 3.2 Product & Design:
          - VP of Product: job_roles/product__design/vp_of_product.md
          - VP of Design: job_roles/product__design/vp_of_design.md
          - Data Scientist: job_roles/product__design/data_scientist.md
          - Product Designer: job_roles/product__design/product_designer.md
          - Product Manager: job_roles/product__design/product_manager.md
          - Technical PM: job_roles/product__design/technical_pm.md
          - Technical PgM: job_roles/product__design/technical_pgm.md
          - UX Writer: job_roles/product__design/ux_writer.md
          - User Researcher: job_roles/product__design/user_researcher.md
      - 3.3 Go-To-Market (Sales & Marketing):
          - VP of Marketing: job_roles/go_to_market_sales__marketing/vp_of_marketing.md
          - VP of Sales: job_roles/go_to_market_sales__marketing/vp_of_sales.md
          - Account Executive: job_roles/go_to_market_sales__marketing/account_executive.md
          - Brand Marketing: job_roles/go_to_market_sales__marketing/brand_marketing.md
          - Comms - PR: job_roles/go_to_market_sales__marketing/comms_pr.md
          - Customer Success: job_roles/go_to_market_sales__marketing/customer_success.md
          - Public Policy Mgr: job_roles/go_to_market_sales__marketing/public_policy_mgr.md
          - Sales Dev Rep: job_roles/go_to_market_sales__marketing/sales_dev_rep.md
          - Solutions Eng: job_roles/go_to_market_sales__marketing/solutions_eng.md
      - 3.4 G&A (General & Administrative):
          - VP of Finance: job_roles/ga_general__administrative/vp_of_finance.md
          - VP of People: job_roles/ga_general__administrative/vp_of_people.md
          - Controller: job_roles/ga_general__administrative/controller.md
          - Corp Counsel: job_roles/ga_general__administrative/corp_counsel.md
          - Employment Counsel: job_roles/ga_general__administrative/employment_counsel.md
          - FP&A Analyst: job_roles/ga_general__administrative/fpa_analyst.md
          - HR Partner: job_roles/ga_general__administrative/hr_partner.md
          - Strategy & Ops: job_roles/ga_general__administrative/strategy__ops.md
          - Workplace Mgr: job_roles/ga_general__administrative/workplace_mgr.md
      - 4. Specialized Squads:
          - AI Ethics & Safety: job_roles/4._specialized_squads_cross_functional_teams/ai_ethics__safety.md
          - Accessibility (A11y): job_roles/4._specialized_squads_cross_functional_teams/accessibility_a11y.md
          - Acquisition (SEO): job_roles/4._specialized_squads_cross_functional_teams/acquisition_seo.md
          - Cloud Migration Squad: job_roles/4._specialized_squads_cross_functional_teams/cloud_migration_squad.md
          - Data Platform: job_roles/4._specialized_squads_cross_functional_teams/data_platform.md
          - Developer Experience: job_roles/4._specialized_squads_cross_functional_teams/developer_experience.md
          - Enterprise Launch: job_roles/4._specialized_squads_cross_functional_teams/enterprise_launch.md
          - Event Strategy: job_roles/4._specialized_squads_cross_functional_teams/event_strategy.md
          - IPO Audit Ready: job_roles/4._specialized_squads_cross_functional_teams/ipo_audit_ready.md
          - Internationalization: job_roles/4._specialized_squads_cross_functional_teams/internationalization.md
          - Mobile Platform: job_roles/4._specialized_squads_cross_functional_teams/mobile_platform.md
          - Monetization: job_roles/4._specialized_squads_cross_functional_teams/monetization.md
          - Privacy (GDPR): job_roles/4._specialized_squads_cross_functional_teams/privacy_gdpr.md
          - Security Red Team: job_roles/4._specialized_squads_cross_functional_teams/security_red_team.md
          - Strategic Partner: job_roles/4._specialized_squads_cross_functional_teams/strategic_partner.md
          - Sustainability (ESG): job_roles/4._specialized_squads_cross_functional_teams/sustainability_esg.md
  - Interview Questions:
      - Backend Engineer: interview_questions/engineering__technology/backend_engineer.md
      - Data Analysis: interview_questions/data_analysis.md
      - Data Engineering: interview_questions/data_engineering.md
      - Data Infrastructure: interview_questions/data_infrastructure.md
      - Data Science: interview_questions/data_science.md
      - Frontend Engineer: interview_questions/engineering__technology/frontend_engineer.md
      - Golang: interview_questions/golang.md
      - Java: interview_questions/java.md
      - JavaScript: interview_questions/javascript.md
      - Kotlin: interview_questions/kotlin.md
      - Protocol Buffers: interview_questions/protocol_buffers.md
      - Python: interview_questions/python.md
      - Software Engineering: interview_questions/software_engineering.md
      - SQL: interview_questions/sql.md
      - System Design: interview_questions/system_design.md
      - TypeScript: interview_questions/typescript.md
  - Style Guides:
      - Bash: style_guides/bash/bash_style_guide.md
      - C++: style_guides/cpp/cpp_style_guide.md
      - CSS: style_guides/css/css_style_guide.md
      - Golang: style_guides/golang/golang_style_guide.md
      - HTML: style_guides/html/html_style_guide.md
      - Java: style_guides/java/java_style_guide.md
      - JavaScript: style_guides/javascript/javascript_style_guide.md
      - JSON: style_guides/json/json_style_guide.md
      - Kotlin: style_guides/kotlin/kotlin_style_guide.md
      - Markdown: style_guides/markdown/markdown_style_guide.md
      - Proto: style_guides/proto/proto_style_guide.md
      - Python: style_guides/python/python_style_guide.md
      - Rust: style_guides/rust/rust_style_guide.md
      - SQL: style_guides/sql/sql_style_guide.md
      - Starlark: style_guides/starlark/starlark_style_guide.md
      - TypeScript: style_guides/typescript/typescript_style_guide.md
      - YAML: style_guides/yaml/yaml_style_guide.md
      - Zsh: style_guides/zsh/zsh_style_guide.md
  - Architecture Decision Records:
      - Template: adr/template.md
      - Example (Architecture Decision): adr/0001_example_architecture_decision.md
  - Technical Design Doc: technical_design_doc.md
