site_name: DevSet
site_url: https://toxicoder.github.io/devset/

theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

nav:
  - Home: index.md
  - Job Role Organization:
      - Overview: JOB_ROLE_ORGANIZATION/JOB_ROLE_ORGANIZATION.md
      - 3.0 Executive Leadership:
          - CEO: JOB_ROLE_ORGANIZATION/3.0 Executive Leadership/CEO.md
          - CFO: JOB_ROLE_ORGANIZATION/3.0 Executive Leadership/CFO.md
          - CLO: JOB_ROLE_ORGANIZATION/3.0 Executive Leadership/CLO.md
          - CPO: JOB_ROLE_ORGANIZATION/3.0 Executive Leadership/CPO.md
          - CRO: JOB_ROLE_ORGANIZATION/3.0 Executive Leadership/CRO.md
          - CTO: JOB_ROLE_ORGANIZATION/3.0 Executive Leadership/CTO.md
      - 3.1 Engineering & Technology:
          - VP of Engineering: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/VP of Engineering.md
          - Director of App Dev: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Director of App Dev.md
          - Director of Infrastructure: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Director of Infrastructure.md
          - Backend Engineer: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Backend Engineer.md
          - Data Engineer: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Data Engineer.md
          - Frontend Engineer: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Frontend Engineer.md
          - Mobile Engineer: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Mobile Engineer.md
          - QA Engineer: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/QA Engineer.md
          - Security Engineer: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Security Engineer.md
          - Site Reliability Eng: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Site Reliability Eng.md
          - Software Engineer: JOB_ROLE_ORGANIZATION/3.1 Engineering & Technology/Software Engineer.md
      - 3.2 Product & Design:
          - VP of Product: JOB_ROLE_ORGANIZATION/3.2 Product & Design/VP of Product.md
          - VP of Design: JOB_ROLE_ORGANIZATION/3.2 Product & Design/VP of Design.md
          - Data Scientist: JOB_ROLE_ORGANIZATION/3.2 Product & Design/Data Scientist.md
          - Product Designer: JOB_ROLE_ORGANIZATION/3.2 Product & Design/Product Designer.md
          - Product Manager: JOB_ROLE_ORGANIZATION/3.2 Product & Design/Product Manager.md
          - Technical PM: JOB_ROLE_ORGANIZATION/3.2 Product & Design/Technical PM.md
          - Technical PgM: JOB_ROLE_ORGANIZATION/3.2 Product & Design/Technical PgM.md
          - UX Writer: JOB_ROLE_ORGANIZATION/3.2 Product & Design/UX Writer.md
          - User Researcher: JOB_ROLE_ORGANIZATION/3.2 Product & Design/User Researcher.md
      - 3.3 Go-To-Market (Sales & Marketing):
          - VP of Marketing: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/VP of Marketing.md
          - VP of Sales: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/VP of Sales.md
          - Account Executive: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/Account Executive.md
          - Brand Marketing: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/Brand Marketing.md
          - Comms - PR: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/Comms - PR.md
          - Customer Success: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/Customer Success.md
          - Public Policy Mgr: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/Public Policy Mgr.md
          - Sales Dev Rep: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/Sales Dev Rep.md
          - Solutions Eng: JOB_ROLE_ORGANIZATION/3.3 Go-To-Market (Sales & Marketing)/Solutions Eng.md
      - 3.4 G&A (General & Administrative):
          - VP of Finance: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/VP of Finance.md
          - VP of People: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/VP of People.md
          - Controller: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/Controller.md
          - Corp Counsel: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/Corp Counsel.md
          - Employment Counsel: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/Employment Counsel.md
          - FP&A Analyst: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/FP&A Analyst.md
          - HR Partner: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/HR Partner.md
          - Strategy & Ops: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/Strategy & Ops.md
          - Workplace Mgr: JOB_ROLE_ORGANIZATION/3.4 G&A (General & Administrative)/Workplace Mgr.md
      - 4. Specialized Squads:
          - AI Ethics & Safety: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/AI Ethics & Safety.md
          - Accessibility (A11y): JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Accessibility (A11y).md
          - Acquisition (SEO): JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Acquisition (SEO).md
          - Cloud Migration Squad: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Cloud Migration Squad.md
          - Data Platform: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Data Platform.md
          - Developer Experience: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Developer Experience.md
          - Enterprise Launch: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Enterprise Launch.md
          - Event Strategy: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Event Strategy.md
          - IPO Audit Ready: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/IPO Audit Ready.md
          - Internationalization: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Internationalization.md
          - Mobile Platform: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Mobile Platform.md
          - Monetization: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Monetization.md
          - Privacy (GDPR): JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Privacy (GDPR).md
          - Security Red Team: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Security Red Team.md
          - Strategic Partner: JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Strategic Partner.md
          - Sustainability (ESG): JOB_ROLE_ORGANIZATION/4. Specialized Squads (Cross-Functional Teams)/Sustainability (ESG).md
  - Interview Questions:
      - Backend Engineer: interview-questions/3.1 Engineering & Technology/Backend Engineer.md
      - Data Analysis: interview-questions/data-analysis.md
      - Data Engineering: interview-questions/data-engineering.md
      - Data Infrastructure: interview-questions/data-infrastructure.md
      - Data Science: interview-questions/data-science.md
      - Frontend Engineer: interview-questions/3.1 Engineering & Technology/Frontend Engineer.md
      - Golang: interview-questions/golang.md
      - Java: interview-questions/java.md
      - JavaScript: interview-questions/javascript.md
      - Kotlin: interview-questions/kotlin.md
      - Protocol Buffers: interview-questions/protocol-buffers.md
      - Python: interview-questions/python.md
      - Software Engineering: interview-questions/software-engineering.md
      - SQL: interview-questions/sql.md
      - System Design: interview-questions/system-design.md
      - TypeScript: interview-questions/typescript.md
  - Style Guides:
      - Bash: style-guides/bash/bash-style-guide.md
      - C++: style-guides/cpp/cpp-style-guide.md
      - CSS: style-guides/css/css-style-guide.md
      - Golang: style-guides/golang/golang-style-guide.md
      - HTML: style-guides/html/html-style-guide.md
      - Java: style-guides/java/java-style-guide.md
      - JavaScript: style-guides/javascript/javascript-style-guide.md
      - JSON: style-guides/json/json-style-guide.md
      - Kotlin: style-guides/kotlin/kotlin-style-guide.md
      - Markdown: style-guides/markdown/markdown-style-guide.md
      - Proto: style-guides/proto/proto-style-guide.md
      - Python: style-guides/python/python-style-guide.md
      - Rust: style-guides/rust/rust-style-guide.md
      - SQL: style-guides/sql/sql-style-guide.md
      - Starlark: style-guides/starlark/starlark-style-guide.md
      - TypeScript: style-guides/typescript/typescript-style-guide.md
      - YAML: style-guides/yaml/yaml-style-guide.md
      - Zsh: style-guides/zsh/zsh-style-guide.md
  - Architecture Decision Records:
      - Template: adr/template.md
      - Example (Architecture Decision): adr/0001-example-architecture-decision.md
  - Technical Design Doc: technical_design_doc.md
