title: DevSet
description: Development Standards and Tooling
url: https://toxicoder.github.io
baseurl: /devset
remote_theme: toxicoder/materialistic-jekyll
plugins:
- jekyll-remote-theme
- jekyll-optional-front-matter
- jekyll-seo-tag
- jekyll-feed
theme_settings:
  palette: palette-1
permalink: pretty
defaults:
- scope:
    path: ''
  values:
    layout: default
    sidebar:
      nav: "docs"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
